=== ssirsika-tibco/xpd-sce-test/tbs-bpm/product/com.tibco.xpd.simulation.feature/plugins/com.tibco.xpd.scheduling/model/calendar.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.tibco.com/calendar" xmlns:calendar="http://www.tibco.com/calendar">
	<complexType name="PublicHolidays">
        <sequence>
			<element name="SingleHoliday" minOccurs="0" maxOccurs="unbounded">
				<complexType>
					<sequence>
						<element name="Name" type="string"></element>
						<element name="StartDate" type="string"></element>
						<element name="EndDate" type="string"></element>
					</sequence>
				</complexType>
			</element>
			<element name="CalculatedHoliday" minOccurs="0" maxOccurs="unbounded">
				<complexType>
					<sequence>
						<element name="Name" type="string"></element>
						<element name="Script" type="string">
							<annotation>
								<documentation>JavaScript which, given a year, will return the date of the holiday in that year.</documentation>
							</annotation>
						</element>
					</sequence>
				</complexType>
			</element>
		</sequence>
	</complexType>

	<complexType name="Calendar">
		<sequence>
			<element name="Name" type="string"></element>
			<element name="Locale" type="string"></element>
			<element name="DefaultWorkingSchedule"
				type="calendar:WorkingSchedule">
			</element>
			<element name="PublicHolidays" type="calendar:PublicHolidays"
				minOccurs="0" maxOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="WorkingSchedule">
		<sequence>
			<element name="WorkingDay" type="calendar:WorkingDay" maxOccurs="unbounded" minOccurs="1"></element>
			<element name="DefaultWorkingTime" type="calendar:WorkingTime"></element>
		</sequence>
	</complexType>

	<complexType name="WorkingDay">
		<sequence>
			<element name="DayOfWeek" type="int"></element>
			<element name="WorkingTime" type="calendar:WorkingTime" minOccurs="0" maxOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="WorkingTime">
		<sequence>
			<element name="TimeSlot" type="calendar:TimeSlot" minOccurs="1" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<element name="Calendar" type="calendar:Calendar"></element>

	<complexType name="TimeSlot">
		<sequence>
			<element name="StartTime" type="string"></element>
			<element name="EndTime" type="string"></element>
		</sequence>
	</complexType>

</schema>

=== ssirsika-tibco/xpd-sce-test/tbs-bpm/product/com.tibco.sce.simulation.feature/plugins/com.tibco.xpd.scheduling/resources/calendars/calendar_default.xml
<?xml version="1.0" encoding="UTF-8"?>
<calendar:Calendar xmlns:calendar="http://www.tibco.com/calendar" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.tibco.com/calendar ../../model/calendar.xsd ">
  <Name>Default</Name>
  <Locale>default</Locale>
  <DefaultWorkingSchedule>
    <WorkingDay>
      <DayOfWeek>2</DayOfWeek>
    </WorkingDay>
    <WorkingDay>
      <DayOfWeek>3</DayOfWeek>
    </WorkingDay>
    <WorkingDay>
      <DayOfWeek>4</DayOfWeek>
    </WorkingDay>
    <WorkingDay>
      <DayOfWeek>5</DayOfWeek>
    </WorkingDay>
    <WorkingDay>
      <DayOfWeek>6</DayOfWeek>
    </WorkingDay>
    <DefaultWorkingTime>
      <TimeSlot>
        <StartTime>09:00:00</StartTime>
        <EndTime>12:30:00</EndTime>
      </TimeSlot>
      <TimeSlot>
        <StartTime>13:30:00</StartTime>
        <EndTime>17:30:00</EndTime>
      </TimeSlot>
    </DefaultWorkingTime>
  </DefaultWorkingSchedule>
</calendar:Calendar>
